CREATE TABLE AUTHOR_TBL(
    AUTHOR_CODE NUMBER(5) PRIMARY KEY,
    AUTHOR_NAME VARCHAR2(20) NOT NULL,
    CONTACT_NO NUMBER(10));
    
INSERT INTO AUTHOR_TBL VALUES(1,'RobinSharma',8800799224);
INSERT INTO AUTHOR_TBL VALUES(2,'R.K.Narayan',9971935000);
INSERT INTO AUTHOR_TBL VALUES(3,'Paulo Coelho',1234567890);

COMMIT;


CREATE TABLE BOOK_TBL(
     ISBN VARCHAR2(10) PRIMARY KEY,
     BOOK_TITLE VARCHAR2(20) NOT NULL,
     BOOK_TYPE CHAR(1)CHECK (BOOK_TYPE IN ('G', 'T')),
     AUTHOR_CODE NUMBER(5) NOT NULL REFERENCES AUTHOR_TBL(AUTHOR_CODE),
     BOOK_COST NUMBER(8,2) NOT NULL);
     
     SELECT * FROM BOOK_TBL;
     SELECT * FROM AUTHOR_TBL;